### ISSUE TITLE
Add broker/results for in memory queue

### ISSUE THREAD

**Issue by ericschmar** [kalbhor/Tasqueue#1]
Consider adding an in memory implementation for broker/results. This would be useful for local development/testing.

**Comment by kalbhor** [comment]
This is a good suggestion. The test cases contain a simple in-memory implementation, I guess that itself can be added.

**Comment by ericschmar** [comment]
> This is a good suggestion. The test cases contain a simple in-memory implementation, I guess that itself can be added.

sure, that'd be perfect
