### ISSUE TITLE
Replacing logrus with logf

### ISSUE THREAD

**Issue by iamd3vil** [kalbhor/Tasqueue#15]
Should we replace logrus with logf (github.com/zerodha/logf) ?

Also there should be a way to configure logging for both the lib and all the brokers, result backends. Currently we just do `INFO` messages which users of the lib might not want.

If you are okay with this, I will send a PR and we can discuss the API.

**Comment by kalbhor** [comment]
Yes, we should replace logrus. I think we can pass a logger to the various backends/brokers to maintain consistency
