### ISSUE TITLE
Configuring concurrency per task

### ISSUE THREAD

**Issue by iamd3vil** [kalbhor/Tasqueue#5]
Currently `Concurrency` and `Queue` is part of `ServerOpts`. This restricts all tasks registered on the server to have the same concurrency. The only way to configure different concurrency is to have a different server per task. I think it would be better if it's possible to define concurrency per task. This applies to the `Queue` as well. We can have different queues for each task as well. This would make it more efficient than everything in the same queue.

What are your thoughts on this?

**Comment by kalbhor** [comment]
This makes sense to have, seems to be straightforward implementation wise as well - In the main `Start(ctx context.Context)` method, iterate over the registered tasks & run multiple `consume` and `process` go routines.

**Comment by iamd3vil** [comment]
I can give it a try if you are okay with it?
